const DUMMY_EVENTS = [
  {
    _id: "a71f9756-fd61-4514-977d-261e38345d55",
    title: "Cabbage Soup",
    description: "Make and share this Cabbage Soup recipe from Food.com.",
    prep: 20,
    cook: 30,
    category: "Vegetable",
    servings: "4",
    published: "1999-09-19T00:00:00.000Z",
    tags: [
      "Low Protein",
      "Vegan",
      "Low Cholesterol",
      "Healthy",
      "Winter",
      "< 60 Mins",
      "Easy",
    ],
    ingredients: {
      "plain tomato juice": "46",
      cabbage: "4",
      onion: "1",
      carrots: "2",
      celery: "1",
    },
    images: [
      "https://img.sndimg.com/food/image/upload/w_555,h_416,c_fit,fl_progressive,q_95/v1/img/recipes/42/picVEMxk8.jpg",
    ],
    instructions: [
      "Mix everything together and bring to a boil.",
      "Reduce heat and simmer for 30 minutes (longer if you prefer your veggies to be soft).",
      "Refrigerate until cool.",
      "Serve chilled with sour cream.",
    ],
    nutrition: {
      calories: "103.6",
      fat: "0.4",
      saturated: "0.1",
      sodium: "959.3",
      carbohydrates: "25.1",
      fiber: "4.8",
      sugar: "17.7",
      protein: "4.3",
    },
  },
  {
    _id: "774b0956-1286-48bf-85a2-7f5530d66deb",
    title: "Low-Fat Berry Blue Frozen Dessert",
    description:
      "Make and share this Low-Fat Berry Blue Frozen Dessert recipe from Food.com.",
    prep: 45,
    cook: 240,
    category: "Frozen Desserts",
    servings: "4",
    published: "1999-08-09T00:00:00.000Z",
    tags: [
      "Dessert",
      "Low Protein",
      "Low Cholesterol",
      "Healthy",
      "Free Of...",
      "Summer",
      "Weeknight",
      "Freezer",
      "Easy",
    ],
    ingredients: {
      blueberries: "4",
      "granulated sugar": "1/4",
      "vanilla yogurt": "1",
      "lemon juice": "1",
    },
    images: [
      "https://img.sndimg.com/food/image/upload/w_555,h_416,c_fit,fl_progressive,q_95/v1/img/recipes/38/YUeirxMLQaeE1h3v3qnM_229%20berry%20blue%20frzn%20dess.jpg",
      "https://img.sndimg.com/food/image/upload/w_555,h_416,c_fit,fl_progressive,q_95/v1/img/recipes/38/AFPDDHATWzQ0b1CDpDAT_255%20berry%20blue%20frzn%20dess.jpg",
      "https://img.sndimg.com/food/image/upload/w_555,h_416,c_fit,fl_progressive,q_95/v1/img/recipes/38/UYgf9nwMT2SGGJCuzILO_228%20berry%20blue%20frzn%20dess.jpg",
      "https://img.sndimg.com/food/image/upload/w_555,h_416,c_fit,fl_progressive,q_95/v1/img/recipes/38/PeBMJN2TGSaYks2759BA_20140722_202142.jpg",
      "https://img.sndimg.com/food/image/upload/w_555,h_416,c_fit,fl_progressive,q_95/v1/img/recipes/38/picuaETeN.jpg",
      "https://img.sndimg.com/food/image/upload/w_555,h_416,c_fit,fl_progressive,q_95/v1/img/recipes/38/pictzvxW5.jpg",
    ],
    instructions: [
      "Toss 2 cups berries with sugar.",
      "Let stand for 45 minutes, stirring occasionally.",
      "Transfer berry-sugar mixture to food processor.",
      "Add yogurt and process until smooth.",
      "Strain through fine sieve. Pour into baking pan (or transfer to ice cream maker and process according to manufacturers' directions). Freeze uncovered until edges are solid but centre is soft.  Transfer to processor and blend until smooth again.",
      "Return to pan and freeze until edges are solid.",
      "Transfer to processor and blend until smooth again.",
      "Fold in remaining 2 cups of blueberries.",
      "Pour into plastic mold and freeze overnight. Let soften slightly to serve.",
    ],
    nutrition: {
      calories: "170.9",
      fat: "2.5",
      saturated: "1.3",
      sodium: "29.8",
      carbohydrates: "37.1",
      fiber: "3.6",
      sugar: "30.2",
      protein: "3.2",
    },
  },
  {
    _id: "1a2a1e8b-a56c-4c38-ba94-89ab19e21fe6",
    title: "Chicken Breasts Lombardi",
    description:
      "Make and share this Chicken Breasts Lombardi recipe from Food.com.",
    prep: 45,
    cook: 30,
    category: "Chicken Breast",
    servings: "6",
    published: "1999-08-14T00:00:00.000Z",
    tags: [
      "Chicken",
      "Poultry",
      "Meat",
      "European",
      "Very Low Carbs",
      "Weeknight",
      "Oven",
      "< 4 Hours",
    ],
    ingredients: {
      "fresh mushrooms": "2",
      butter: "1/3",
      "boneless skinless chicken breast halves": "12",
      flour: "1/2",
      marsala: "3/4",
      "chicken broth": "1/2",
      salt: "1/2",
      "mozzarella cheese": "1/2",
      "parmesan cheese": "1/2",
      "green onion": "1/4",
    },
    images: [
      "https://img.sndimg.com/food/image/upload/w_555,h_416,c_fit,fl_progressive,q_95/v1/img/recipes/49/m1z1F8S5mAZgyImm5zYw_Lombardi%20Chicken%203.jpg",
      "https://img.sndimg.com/food/image/upload/w_555,h_416,c_fit,fl_progressive,q_95/v1/img/recipes/49/01481162521.jpeg",
      "https://img.sndimg.com/food/image/upload/w_555,h_416,c_fit,fl_progressive,q_95/v1/img/recipes/49/Sa0Yu0UyRoyh1B03oLnD_20161102_174049.jpg",
      "https://img.sndimg.com/food/image/upload/w_555,h_416,c_fit,fl_progressive,q_95/v1/img/recipes/49/01477708512.jpeg",
      "https://img.sndimg.com/food/image/upload/w_555,h_416,c_fit,fl_progressive,q_95/v1/img/recipes/49/tHou0UsyTiAsfQo29Fpi_Lombardi%20Chicken%202.jpg",
      "https://img.sndimg.com/food/image/upload/w_555,h_416,c_fit,fl_progressive,q_95/v1/img/recipes/49/X2b0bl8aTGivq4ErsD3g_Lombardi%20chicken%201.jpg",
      "https://img.sndimg.com/food/image/upload/w_555,h_416,c_fit,fl_progressive,q_95/v1/img/recipes/49/picvZU6rd.jpg",
    ],
    instructions: [
      "Cook mushrooms in 2 tbsp butter in a large  skillet, stirring constantly, just   until tender.",
      'Remove from heat; set aside.  Cut each chicken breast half in  half lengthwise.   Place each piece of chicken  between two sheets of wax paper; flatten to  1/8" thickness, using a meat  mallet or rolling pin.',
      "Dredge chicken pieces in flour.",
      "Place 5 or 6  pieces of chicken in 1 to 2  tbsp butter in a  large skillet; cook over medium  heat 3 to 4 minutes on each  side or until  golden.",
      'Place chicken in a lightly  greased 13x9" baking dish,  overlapping  edges.',
      "Repeat procedure with  remaining chicken and butter.",
      "Reserve pan  drippings in skillet.  Sprinkle  reserved mushrooms over chicken.",
      "Add wine and  broth to skillet.  Bring to a boil;  reduce heat, and simmer,  uncovered, 10  minutes, stirring occasionally.",
      "Stir in salt and pepper.",
      "Pour  sauce over  chicken.",
      "Combine cheeses and green  onions; sprinkle over chicken.",
      "Bake  uncovered at 450 for 12 to 14 minutes.",
      'Broil 5 1/2" away from heat 1 to  2  minutes or until browned.',
    ],
    nutrition: {
      calories: "627.7",
      fat: "24.9",
      saturated: "13",
      sodium: "848.9",
      carbohydrates: "13.7",
      fiber: "0.6",
      sugar: "2",
      protein: "57.9",
    },
  },
];

export function getRecipeById(id) {
  return DUMMY_EVENTS.find((recipe) => recipe._id === id);
}
